import { Contracts } from '../schemas/index.js';

function typeToPython(type: string): string {
  const mapping: Record<string, string> = {
    string: 'str',
    number: 'float | int',
    boolean: 'bool',
    object: 'dict[str, Any]',
    array: 'list[Any]',
  };
  return mapping[type] || 'Any';
}

export function emitPython(contracts: Contracts): string {
  let output = `# Auto-generated from contracts.yaml
# DO NOT EDIT — regenerated by 'hackx contract generate'

from typing import Any, TypedDict, Optional

`;

  // Enum definitions
  if (contracts.enums) {
    for (const [name, values] of Object.entries(contracts.enums)) {
      output += `class ${name}:\n`;
      for (const value of values) {
        output += `    ${value} = "${value}"\n`;
      }
      output += `\n`;
    }
  }

  // Request/response types
  for (const endpoint of contracts.endpoints) {
    const typeName = endpoint.id.replace(/\s+/g, '').replace(/\//g, '_');

    // Request type
    if (endpoint.request) {
      const reqType = typeToPython(endpoint.request.type);
      output += `class ${typeName}Request(TypedDict, total=False):\n`;
      output += `    pass  # ${reqType}\n\n`;
    }

    // Response type
    const respType = typeToPython(endpoint.response.type);
    output += `class ${typeName}Response(TypedDict, total=False):\n`;
    output += `    pass  # ${respType}\n\n`;
  }

  // Contract registry
  output += `ENDPOINTS = {\n`;
  for (const endpoint of contracts.endpoints) {
    output += `    '${endpoint.id}': {\n`;
    output += `        'method': '${endpoint.method}',\n`;
    output += `        'path': '${endpoint.path}',\n`;
    output += `        'description': '${endpoint.description || ''}',\n`;
    output += `    },\n`;
  }
  output += `}\n`;

  return output;
}
