import { Contracts } from '../schemas/index.js';

function typeToTs(type: string): string {
  const mapping: Record<string, string> = {
    string: 'string',
    number: 'number',
    boolean: 'boolean',
    object: 'Record<string, unknown>',
    array: 'unknown[]',
  };
  return mapping[type] || 'unknown';
}

export function emitTypeScript(contracts: Contracts): string {
  let output = `// Auto-generated from contracts.yaml
// DO NOT EDIT — regenerated by 'hackx contract generate'

`;

  // Enum definitions
  if (contracts.enums) {
    for (const [name, values] of Object.entries(contracts.enums)) {
      output += `export const ${name} = {\n`;
      for (const value of values) {
        output += `  ${value}: '${value}' as const,\n`;
      }
      output += `} as const;\n`;
      output += `export type ${name} = typeof ${name}[keyof typeof ${name}];\n\n`;
    }
  }

  // Request/response types
  for (const endpoint of contracts.endpoints) {
    const typeName = endpoint.id.replace(/\s+/g, '').replace(/\//g, '_');

    // Request type
    if (endpoint.request) {
      const reqType = typeToTs(endpoint.request.type);
      output += `export type ${typeName}Request = ${reqType};\n`;
    }

    // Response type
    const respType = typeToTs(endpoint.response.type);
    output += `export type ${typeName}Response = ${respType};\n\n`;
  }

  // Contract registry
  output += `export const Endpoints = {\n`;
  for (const endpoint of contracts.endpoints) {
    output += `  '${endpoint.id}': {\n`;
    output += `    method: '${endpoint.method}',\n`;
    output += `    path: '${endpoint.path}',\n`;
    output += `    description: '${endpoint.description || ''}',\n`;
    output += `  },\n`;
  }
  output += `} as const;\n`;

  return output;
}
